/**
 * generated by Xtext 2.10.1
 */
package org.ne.xtext.example.program.programDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.xtext.xbase.impl.XBlockExpressionImpl;

import org.ne.xtext.example.program.programDsl.Body;
import org.ne.xtext.example.program.programDsl.ProgramDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BodyImpl extends XBlockExpressionImpl implements Body
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BodyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ProgramDslPackage.Literals.BODY;
  }

} //BodyImpl
