/*
 * generated by Xtext 2.10.1
 */
package org.ne.xtext.example.program.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.ne.xtext.example.program.ui.internal.ProgramActivator;

public class ProgramDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ProgramActivator.getInstance().getInjector("org.ne.xtext.example.program.ProgramDsl");
	}

}
