/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl;

import org.eclipse.xtext.xbase.compiler.XbaseCompiler;
import org.eclipse.xtext.xbase.scoping.batch.ImplicitlyImportedFeatures;
import org.eclipse.xtext.xbase.scoping.featurecalls.OperatorMapping;
import org.eclipse.xtext.xbase.typesystem.computation.ITypeComputer;
import org.xtext.example.mydsl.compiler.MyDslCompiler;
import org.xtext.example.mydsl.compiler.MyDslTypeComputer;
import org.xtext.example.mydsl.scoping.MyDslImplicitlyImportedFeatures;
import org.xtext.example.mydsl.scoping.MyDslOperatorMapping;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {

	public Class<? extends OperatorMapping> bindOperatorMapping() {
		return MyDslOperatorMapping.class;
	}

	public Class<? extends XbaseCompiler> bindXbaseCompiler() {
		return MyDslCompiler.class;
	}

	public Class<? extends ITypeComputer> bindITypeComputer() {
		return MyDslTypeComputer.class;
	}

	public Class<? extends ImplicitlyImportedFeatures> bindImplicitlyImportedFeatures() {
		return MyDslImplicitlyImportedFeatures.class;
	}

}
