/*
 * generated by Xtext 2.10.1
 */
package org.ne.xtext.example.program.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.ne.xtext.example.program.parser.antlr.internal.InternalProgramDslParser;
import org.ne.xtext.example.program.services.ProgramDslGrammarAccess;

public class ProgramDslParser extends AbstractAntlrParser {

	@Inject
	private ProgramDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalProgramDslParser createParser(XtextTokenStream stream) {
		return new InternalProgramDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public ProgramDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ProgramDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
