/*
 * generated by Xtext 2.10.1
 */
package org.ne.xtext.example.program.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.ne.xtext.example.program.ui.internal.ProgramActivator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ProgramDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ProgramActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ProgramActivator.getInstance().getInjector(ProgramActivator.ORG_NE_XTEXT_EXAMPLE_PROGRAM_PROGRAMDSL);
	}
	
}
