/**
 * generated by Xtext 2.10.1
 */
package org.ne.xtext.example.program.ui.contentassist;

import org.ne.xtext.example.program.ui.contentassist.AbstractProgramDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ProgramDslProposalProvider extends AbstractProgramDslProposalProvider {
}
