/**
 * generated by Xtext 2.10.1
 */
package org.ne.xtext.example.program.scoping;

import org.ne.xtext.example.program.scoping.AbstractProgramDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ProgramDslScopeProvider extends AbstractProgramDslScopeProvider {
}
