/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractMyDslScopeProvider extends XbaseBatchScopeProvider {
}
