/**
 * generated by Xtext 2.10.1
 */
package org.ne.xtext.example.program.programDsl;

import org.eclipse.xtext.xbase.XBlockExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Body</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.ne.xtext.example.program.programDsl.ProgramDslPackage#getBody()
 * @model
 * @generated
 */
public interface Body extends XBlockExpression
{
} // Body
