/**
 * generated by Xtext 2.10.1
 */
package org.ne.xtext.example.program.validation;

import org.ne.xtext.example.program.validation.AbstractProgramDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ProgramDslValidator extends AbstractProgramDslValidator {
}
