/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.ui.editor;

import org.eclipse.xtext.xbase.ui.editor.XbaseEditor;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class MyDslEditor extends XbaseEditor {
}
