/**
 * generated by Xtext 2.10.1
 */
package org.ne.xtext.example.program.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ui.editor.model.XtextDocumentProvider;
import org.ne.xtext.example.program.ui.AbstractProgramDslUiModule;
import org.ne.xtext.example.program.ui.documentprovider.ProgramDocumentProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ProgramDslUiModule extends AbstractProgramDslUiModule {
  @Override
  public Class<? extends XtextDocumentProvider> bindXtextDocumentProvider() {
    return ProgramDocumentProvider.class;
  }
  
  public ProgramDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
