/*
 * generated by Xtext 2.10.1
 */
package org.ne.xtext.example.program.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractProgramDslScopeProvider extends XbaseBatchScopeProvider {
}
