/**
 * generated by Xtext 2.10.1
 */
package org.ne.xtext.example.program.ui.quickfix;

import org.eclipse.xtext.xbase.ui.quickfix.XbaseQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class ProgramDslQuickfixProvider extends XbaseQuickfixProvider {
}
